stages:
  - build
  - test
  - clean
build:
  stage: build
  script:
    - bash build_gtest.sh && mkdir -p build && cd build && cmake .. & make
  artifacts:
    paths:
      - ./

test:
  stage: test
  script:
    - ./
    - ./testRunner --gtest_output="xml:./"
  artifacts:
    when: always
    paths: 
      - report/
    reports:
      junit: report/report.xml
  

clean:
  stage: clean
  script:
    - make clean
