stages:
  - build
  - test

build:
  stage: build
  tags: 
    - runner2
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  stage: test
  tags:
    - runner2
  script:
    - make

    

  
