stages:
  - build
  - test
  - clean
build:
  stage: build
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths: 
      - report/
    reports:
      junit: report/report.xml
  

clean:
  stage: clean
  script:
    - make clean
