stages:
  - build
  - test

build:
  tags: runner_test
  stage: build
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  tags: runner_test
  stage: test
  script:
    - pwd
    - make

    

  
