stages:
  - build
  - test
  - clean

build:
  stage: build
  tags: 
    - runner2
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  stage: test
  tags:
    - runner2
  script:
    - make

clean:
  stage: clean
  tags:
    - runner2
  script:
    - make clean


    

  
