stages:
  - build
  - test
  - clean
build:
  stage: build
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./*
      - ../*
      - build/*

test:
  stage: test
  script:
    - cd build && ./testRunner
    #- cd testing && make && make run &&./test --gtest_output="xml:./"
  artifacts:
    when: always
    paths: 
      - report/
    reports:
      junit: report/report.xml
  

clean:
  stage: clean
  script:
    - make clean
