build:
  script:
    - apt-get update -y
    - apt install sudo -y
    - sudo apt-get -y install build-essential cmake libpthread-stubs0-dev
    - cd googletest/ && mkdir -p build && cd $_ && cmake .. && make
    - make
    #&& cd ../../../../../ && make
    #- ./test_exe
    
