test:
  script:
    - apt-get update -y
    - apt install sudo -y
    - sudo apt-get install build-essential cmake -y && cd vendor/google/googletest/googletest/ && mkdir build && cd $_ && cmake .. && make 
    #&& cd ../../../../../ && make
    #- ./test_exe
    
