stages:
  - build
  - test

build:
  jobs:
    tags:
      - build
  stage: build
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  jobs:
    tags:
      - build
  stage: test
  script:
    - pwd
    - make

    

  
