stages:
  - build
  - test
  - clean

build:
  stage: build
  tags:
    - build
  script:
    - bash build_gtest.sh
  artifacts:
    paths:
      - ./

test:
  stage: test
  tags:
    - build
  script:
    - make test

clean:
  stage: clean
  tags:
    - build
  script:
    - make clean


    

  
